#!/bin/sh

cflags="-I/usr/local/include/3dengfx/src -DHAVE_CONFIG_H"

libs="-l3dengfx -lGL -lGLU -lCg -lCgGL -lbz2"

if test $# -eq 0; then
      echo "oug" 1>&2
      exit 1
fi

while test $# -gt 0; do
	case $1 in
	--cflags)
		echo $cflags `sdl-config --cflags`
		;;

	--libs)
		echo $libs `sdl-config --libs` `pkg-config libpng --libs`
		;;
	esac
	shift
done
