n3dmath2_obj =\
	src/n3dmath2/n3dmath2.o\
	src/n3dmath2/n3dmath2_mat.o\
	src/n3dmath2/n3dmath2_vec.o\
	src/n3dmath2/n3dmath2_qua.o\
	src/n3dmath2/n3dmath2_ray.o\
	src/n3dmath2/n3dmath2_qdr.o\
	src/n3dmath2/n3dmath2_sph.o
