3dengfx_obj = \
	src/3dengfx/3denginefx.o\
	src/3dengfx/textures.o\
	src/3dengfx/camera.o\
	src/3dengfx/material.o\
	src/3dengfx/object.o\
	src/3dengfx/texman.o\
	src/3dengfx/light.o\
	src/3dengfx/ggen.o\
	src/3dengfx/3dscene.o\
	src/3dengfx/sceneloader.o\
	src/3dengfx/gfxprog.o\
	src/3dengfx/psys.o\
	src/3dengfx/scfield.o\
	src/3dengfx/rend_curve.o\
	src/3dengfx/sdrman.o\
	src/3dengfx/ply.o\
	src/3dengfx/shadows.o
